export { default as Home } from './home/Home'
export { default as About } from './about/About'
export { default as Skills } from './skills/Skills'
export { default as Portfolio } from './portfolio/Portfolio'
export { default as Testimonials } from './testimonials/Testimonials'